import { ProjectTypeOption, WorkflowPhase, CreditApplication } from './types';

export const PROJECT_TYPE_OPTIONS: ProjectTypeOption[] = [
  {
    id: 'construction',
    label: 'Construction de Logement',
    icon: 'Hammer',
    description: 'Édification de maison individuelle ou villa sur terrain titré.',
    minAmount: 5000000,
    maxAmount: 60000000,
    defaultAmount: 15000000,
  },
  {
    id: 'terrain',
    label: 'Acquisition de Terrain',
    icon: 'MapPin',
    description: 'Achat de parcelle titrée destinée à un usage d\'habitation.',
    minAmount: 3000000,
    maxAmount: 25000000,
    defaultAmount: 6000000,
  },
  {
    id: 'social',
    label: 'Logement Social (SIC/MAETUR)',
    icon: 'Building2',
    description: 'Acquisition dans les programmes immobiliers publics agréés.',
    minAmount: 8000000,
    maxAmount: 40000000,
    defaultAmount: 18000000,
  },
  {
    id: 'renovation',
    label: 'Extension ou Rénovation',
    icon: 'Sparkles',
    description: 'Travaux de modernisation, réhabilitation ou surélévation.',
    minAmount: 2000000,
    maxAmount: 20000000,
    defaultAmount: 5000000,
  },
];

export const WORKFLOW_PHASES: WorkflowPhase[] = [
  {
    id: 'phase_1_kyc_savings',
    stepNumber: 1,
    title: 'Phase 1 : Enrôlement, KYC & Constitution Épargne',
    shortTitle: '1. KYC & Épargne',
    description: 'Vérification d\'identité citoyenne, émission du DUC et versements programmés Mobile Money.',
    responsibleActors: ['Agence CFC', 'Direction Commerciale', 'Client'],
  },
  {
    id: 'phase_2_risks_bet',
    stepNumber: 2,
    title: 'Phase 2 : Analyse Technique & Visite de Chantier BET',
    shortTitle: '2. Risques & BET',
    description: 'Expertise contradictoire des devis et visite terrain par le Bureau d\'Études Techniques.',
    responsibleActors: ['Bureau d\'Études Techniques (BET)', 'Direction du Crédit', 'Gestion des Risques (CGR)'],
  },
  {
    id: 'phase_3_committees',
    stepNumber: 3,
    title: 'Phase 3 : Arbitrage Comités Décisionnels (CGR / CRC)',
    shortTitle: '3. Comités CGR/CRC',
    description: 'Examen de conformité prudentielle, passage en Comité de Crédit et émission de la notification d\'accord.',
    responsibleActors: ['Comité de Gestion des Risques (CGR)', 'Comité de Crédit (CRC)', 'Direction Générale / CA'],
  },
  {
    id: 'phase_4_notary_mortgage',
    stepNumber: 4,
    title: 'Phase 4 : Formalisation Notariée & Hypothèque MINDCAF',
    shortTitle: '4. Notaire & Hypothèque',
    description: 'Souscription assurances (Vie, Incendie, TRC), acte notarié et inscription hypothécaire de 1er rang.',
    responsibleActors: ['Notaire', 'Conservation Foncière (MINDCAF)', 'Compagnies d\'Assurance'],
  },
  {
    id: 'phase_5_disbursements',
    stepNumber: 5,
    title: 'Phase 5 : Déblocages Échelonnés (Valeur Disponible)',
    shortTitle: '5. Déblocages Travaux',
    description: 'Mise à disposition par tranches successives conditionnée par les rapports d\'avancement BET.',
    responsibleActors: ['BET', 'Direction du Crédit', 'Sous-Direction Comptabilité Clientèle'],
  },
  {
    id: 'phase_6_closing_release',
    stepNumber: 6,
    title: 'Phase 6 : Extinction de Dette & Mainlevée d\'Hypothèque',
    shortTitle: '6. Mainlevée & Clôture',
    description: 'Décompte d\'apurement final, acte de mainlevée d\'hypothèque et restitution du Titre Foncier original.',
    responsibleActors: ['Sous-Direction Comptabilité Clientèle', 'Notaire', 'Conservation Foncière'],
  },
];

export const INITIAL_MOCK_APPLICATIONS: CreditApplication[] = [
  {
    id: 'APP-04829',
    ducId: 'CFC-2026-DUC-04829',
    customerName: 'MBALLA Jean-Paul',
    projectType: 'construction',
    projectCost: 15000000,
    loanAmount: 12000000,
    savingsBalance: 3000000,
    savingsTarget: 3000000,
    currentPhase: 'phase_2_risks_bet',
    phaseStatus: 'in_progress',
    agency: 'Agence Yaoundé Centre',
    submittedAt: '12/08/2026',
    lastUpdated: '01/09/2026',
    documents: [
      { id: 'd1', category: 'kyc', name: 'CNI légalisée recto-verso', description: 'Pièce d\'identité', required: true, status: 'verified', fileName: 'CNI_Mballa.pdf', fileSize: '1.2 Mo' },
      { id: 'd2', category: 'income', name: '3 derniers bulletins + AVI', description: 'Justificatifs de salaires', required: true, status: 'verified', fileName: 'Salaires_AVI.pdf', fileSize: '2.8 Mo' },
      { id: 'd3', category: 'land', name: 'Titre Foncier N° 4892/Mfoundi', description: 'Preuve de propriété foncière', required: true, status: 'uploaded', fileName: 'TF_4892_Mfoundi.pdf', fileSize: '5.1 Mo' },
      { id: 'd4', category: 'technical', name: 'Plans visés et devis estimatif', description: 'Dossier technique de construction', required: true, status: 'pending_upload' },
    ],
  },
  {
    id: 'APP-04835',
    ducId: 'CFC-2026-DUC-04835',
    customerName: 'ABANDA Eric',
    projectType: 'terrain',
    projectCost: 6000000,
    loanAmount: 4800000,
    savingsBalance: 540000,
    savingsTarget: 1200000,
    currentPhase: 'phase_1_kyc_savings',
    phaseStatus: 'in_progress',
    agency: 'Agence Yaoundé Centre',
    submittedAt: '18/08/2026',
    lastUpdated: '30/08/2026',
    documents: [],
  },
  {
    id: 'APP-04712',
    ducId: 'CFC-2026-DUC-04712',
    customerName: 'FOTSO Michel',
    projectType: 'construction',
    projectCost: 35000000,
    loanAmount: 28000000,
    savingsBalance: 7000000,
    savingsTarget: 7000000,
    currentPhase: 'phase_2_risks_bet',
    phaseStatus: 'pending_review',
    agency: 'Agence Douala Bonanjo',
    submittedAt: '05/08/2026',
    lastUpdated: '28/08/2026',
    documents: [],
  },
  {
    id: 'APP-04655',
    ducId: 'CFC-2026-DUC-04655',
    customerName: 'NGO NSOA Marie',
    projectType: 'social',
    projectCost: 18000000,
    loanAmount: 14400000,
    savingsBalance: 3600000,
    savingsTarget: 3600000,
    currentPhase: 'phase_3_committees',
    phaseStatus: 'pending_review',
    agency: 'Agence Yaoundé Centre',
    submittedAt: '20/07/2026',
    lastUpdated: '25/08/2026',
    documents: [],
  },
  {
    id: 'APP-04590',
    ducId: 'CFC-2026-DUC-04590',
    customerName: 'TCHOUNGUI Alain',
    projectType: 'construction',
    projectCost: 22000000,
    loanAmount: 17600000,
    savingsBalance: 4400000,
    savingsTarget: 4400000,
    currentPhase: 'phase_4_notary_mortgage',
    phaseStatus: 'in_progress',
    agency: 'Agence Sud (Kribi)',
    submittedAt: '10/06/2026',
    lastUpdated: '15/08/2026',
    documents: [],
  },
  {
    id: 'APP-04410',
    ducId: 'CFC-2026-DUC-04410',
    customerName: 'EBAH Rodrigue',
    projectType: 'construction',
    projectCost: 20000000,
    loanAmount: 16000000,
    savingsBalance: 4000000,
    savingsTarget: 4000000,
    currentPhase: 'phase_5_disbursements',
    phaseStatus: 'in_progress',
    agency: 'Agence Ouest (Bafoussam)',
    submittedAt: '15/03/2026',
    lastUpdated: '18/08/2026',
    documents: [],
  },
  {
    id: 'APP-03890',
    ducId: 'CFC-2026-DUC-03890',
    customerName: 'KAMGA Pascal',
    projectType: 'construction',
    projectCost: 12000000,
    loanAmount: 9600000,
    savingsBalance: 2400000,
    savingsTarget: 2400000,
    currentPhase: 'phase_6_closing_release',
    phaseStatus: 'completed',
    agency: 'Agence Yaoundé Centre',
    submittedAt: '10/01/2025',
    lastUpdated: '20/08/2026',
    documents: [],
  },
];
