import type { BoardState, Column, ColumnId, TaskOwnerProfile, TaskTeam } from "./types";

export const columns: Column[] = [
  { id: "kyc_savings", title: "1. Épargne & KYC" },
  { id: "risk_bet", title: "2. Risques & BET" },
  { id: "committees", title: "3. Comités CGR / CRC" },
  { id: "notary_mortgage", title: "4. Notaire & Hypothèque" },
  { id: "disbursements", title: "5. Déblocages Travaux" },
  { id: "closing_release", title: "6. Clôture & Mainlevée" },
];

export const columnIds: ColumnId[] = [
  "kyc_savings",
  "risk_bet",
  "committees",
  "notary_mortgage",
  "disbursements",
  "closing_release",
];

export const tagTones: Record<TaskTeam, string> = {
  "Agence Yaoundé": "bg-blue-500/10 text-blue-700 dark:bg-blue-500/15 dark:text-blue-300",
  "Agence Douala": "bg-emerald-500/10 text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300",
  "Direction Crédit": "bg-purple-500/10 text-purple-700 dark:bg-purple-500/15 dark:text-purple-300",
  "BET Partenaire": "bg-amber-500/10 text-amber-700 dark:bg-amber-500/15 dark:text-amber-300",
  "Comité CRC": "bg-rose-500/10 text-rose-700 dark:bg-rose-500/15 dark:text-rose-300",
  "Étude Notariale": "bg-indigo-500/10 text-indigo-700 dark:bg-indigo-500/15 dark:text-indigo-300",
  "MINDCAF Foncier": "bg-cyan-500/10 text-cyan-700 dark:bg-cyan-500/15 dark:text-cyan-300",
  "Comptabilité SYSTAC": "bg-teal-500/10 text-teal-700 dark:bg-teal-500/15 dark:text-teal-300",
};

export const taskOwners: Record<string, TaskOwnerProfile> = {
  suzanneNga: { name: "Suzanne Nga", tone: "bg-blue-500/20 text-blue-800" },
  briceKamdem: { name: "Brice Kamdem", tone: "bg-emerald-500/20 text-emerald-800" },
  lucienFame: { name: "Lucien Fame", tone: "bg-amber-500/20 text-amber-800" },
  vincentAyuk: { name: "Vincent Ayuk", tone: "bg-purple-500/20 text-purple-800" },
  drEboumbou: { name: "Dr. Eboumbou", tone: "bg-rose-500/20 text-rose-800" },
  meNkouendjin: { name: "Me Nkouendjin", tone: "bg-indigo-500/20 text-indigo-800" },
  henrietteBella: { name: "Henriette Bella", tone: "bg-teal-500/20 text-teal-800" },
};

export const initialBoard: BoardState = {
  kyc_savings: [
    {
      id: "cfc-task-1",
      ducId: "DUC-04829",
      clientName: "ABANDA Eric",
      projectTitle: "Acquisition Villa Olembé",
      amount: "24 000 000 FCFA",
      amountRaw: 24000000,
      equityContribution: "4 800 000 FCFA (20%)",
      daysInStage: 8,
      slaMaxDays: 15,
      agency: "Agence Yaoundé",
      clientId: "cl-1",
      landTitle: "TF N° 12450/Mfoundi",
      cobacRatio: "27.8%",
      decisionStatus: "Apport en constitution",
      title: "DUC-04829 · ABANDA Eric (Yaoundé)",
      description: "Constitution apport personnel cible 20% (4 800 000 FCFA sur 24M FCFA). 3 derniers bulletins validés.",
      priority: "Medium",
      dueDate: "30 Sept 2026",
      progress: 45,
      owner: taskOwners.suzanneNga,
      team: "Agence Yaoundé",
      insights: [
        { label: "Attachments", count: 4 },
        { label: "Comments", count: 2 },
        { label: "Documents", count: 6 },
      ],
    },
    {
      id: "cfc-task-2",
      ducId: "DUC-04910",
      clientName: "FOKAM Emmanuel",
      projectTitle: "Construction R+1 Bafoussam",
      amount: "16 500 000 FCFA",
      amountRaw: 16500000,
      equityContribution: "3 300 000 FCFA (20%)",
      daysInStage: 4,
      slaMaxDays: 15,
      agency: "Agence Douala",
      clientId: "cl-2",
      landTitle: "TF N° 8490/Mifi",
      cobacRatio: "24.5%",
      decisionStatus: "KYC & Épargne initiée",
      title: "DUC-04910 · FOKAM Emmanuel (Bafoussam)",
      description: "Versement initial MTN MoMo 850 000 FCFA. CNI certifiée & acte de mariage sous régime légal reçus.",
      priority: "Low",
      dueDate: "15 Oct 2026",
      progress: 20,
      owner: taskOwners.briceKamdem,
      team: "Agence Douala",
      insights: [
        { label: "Attachments", count: 2 },
        { label: "Comments", count: 1 },
        { label: "Documents", count: 3 },
      ],
    },
    {
      id: "cfc-task-9",
      ducId: "DUC-04988",
      clientName: "ENOW Peter",
      projectTitle: "Acquisition Terrain Lotissement SIC",
      amount: "12 000 000 FCFA",
      amountRaw: 12000000,
      equityContribution: "3 000 000 FCFA (25%)",
      daysInStage: 2,
      slaMaxDays: 15,
      agency: "Agence Douala",
      clientId: "cl-3",
      landTitle: "TF N° 3421/Wouri",
      cobacRatio: "19.2%",
      decisionStatus: "Enrôlement Carthago",
      title: "DUC-04988 · ENOW Peter (Douala Logbessou)",
      description: "Ouverture compte épargne logement Carthago & convention de réservation lotissement SIC.",
      priority: "Low",
      dueDate: "22 Oct 2026",
      progress: 15,
      owner: taskOwners.briceKamdem,
      team: "Agence Douala",
      insights: [
        { label: "Attachments", count: 3 },
        { label: "Comments", count: 0 },
        { label: "Documents", count: 4 },
      ],
    },
  ],
  risk_bet: [
    {
      id: "cfc-task-3",
      ducId: "DUC-04750",
      clientName: "MBALLA Jean-Paul",
      projectTitle: "Construction Villa R+1 (Olembé)",
      amount: "18 500 000 FCFA",
      amountRaw: 18500000,
      equityContribution: "4 200 000 FCFA (22.7%)",
      daysInStage: 18,
      slaMaxDays: 15,
      agency: "Agence Yaoundé",
      clientId: "cl-1",
      landTitle: "TF N° 4892/Mfoundi",
      cobacRatio: "31.2%",
      decisionStatus: "BET Epsilon en cours de contre-visite",
      title: "DUC-04750 · MBALLA Jean-Paul (Olembé)",
      description: "Visite contradictoire BET Epsilon. Devis descriptif 18 500 000 FCFA & permis de bâtir visé MINHDU.",
      priority: "High",
      dueDate: "12 Sept 2026",
      progress: 85,
      owner: taskOwners.lucienFame,
      team: "BET Partenaire",
      insights: [
        { label: "Attachments", count: 8 },
        { label: "Comments", count: 5 },
        { label: "Documents", count: 9 },
      ],
    },
    {
      id: "cfc-task-4",
      ducId: "DUC-04812",
      clientName: "FOTSO Michel",
      projectTitle: "Rénovation Immeuble Bonapriso",
      amount: "35 000 000 FCFA",
      amountRaw: 35000000,
      equityContribution: "10 500 000 FCFA (30%)",
      daysInStage: 11,
      slaMaxDays: 15,
      agency: "Agence Douala",
      clientId: "cl-4",
      landTitle: "TF N° 10214/Wouri",
      cobacRatio: "28.4%",
      decisionStatus: "Contre-expertise foncière requise",
      title: "DUC-04812 · FOTSO Michel (Douala Bonapriso)",
      description: "Analyse solvabilité COBAC (Endettement calculé à 28.4% < 33%). En attente état des droits réels MINDCAF.",
      priority: "High",
      dueDate: "18 Sept 2026",
      progress: 70,
      owner: taskOwners.vincentAyuk,
      team: "Direction Crédit",
      insights: [
        { label: "Attachments", count: 5 },
        { label: "Comments", count: 3 },
        { label: "Documents", count: 7 },
      ],
    },
  ],
  committees: [
    {
      id: "cfc-task-5",
      ducId: "DUC-04655",
      clientName: "NGO NSOA Marie",
      projectTitle: "Acquisition Logement Mbankolo",
      amount: "14 400 000 FCFA",
      amountRaw: 14400000,
      equityContribution: "2 900 000 FCFA (20.1%)",
      daysInStage: 7,
      slaMaxDays: 10,
      agency: "Agence Yaoundé",
      clientId: "cl-5",
      landTitle: "TF N° 7894/Mfoundi",
      cobacRatio: "26.1%",
      decisionStatus: "Accord de principe CRC émis",
      title: "DUC-04655 · NGO NSOA Marie (Mbankolo)",
      description: "Arbitrage Comité de Crédit (CRC). Prêt acquisition logement 14 400 000 FCFA validé sous réserve assurance TRC.",
      priority: "High",
      dueDate: "08 Sept 2026",
      progress: 90,
      owner: taskOwners.drEboumbou,
      team: "Comité CRC",
      insights: [
        { label: "Attachments", count: 11 },
        { label: "Comments", count: 7 },
        { label: "Documents", count: 14 },
      ],
    },
    {
      id: "cfc-task-10",
      ducId: "DUC-04701",
      clientName: "BIYA Christian",
      projectTitle: "Villa Duplex Odza",
      amount: "28 000 000 FCFA",
      amountRaw: 28000000,
      equityContribution: "7 000 000 FCFA (25%)",
      daysInStage: 12,
      slaMaxDays: 10,
      agency: "Agence Yaoundé",
      clientId: "cl-1",
      landTitle: "TF N° 11024/Mfoundi",
      cobacRatio: "29.8%",
      decisionStatus: "Quorum CGR réuni, visa DGA attendu",
      title: "DUC-04701 · BIYA Christian (Odza Auberge)",
      description: "Dossier en arbitrage CGR. Validation de la dérogation sur l'apport en compte bloqué épargne.",
      priority: "Medium",
      dueDate: "14 Sept 2026",
      progress: 65,
      owner: taskOwners.drEboumbou,
      team: "Comité CRC",
      insights: [
        { label: "Attachments", count: 7 },
        { label: "Comments", count: 4 },
        { label: "Documents", count: 11 },
      ],
    },
  ],
  notary_mortgage: [
    {
      id: "cfc-task-6",
      ducId: "DUC-04590",
      clientName: "TCHOUNGUI Alain",
      projectTitle: "Résidence Balnéaire Kribi",
      amount: "22 000 000 FCFA",
      amountRaw: 22000000,
      equityContribution: "5 500 000 FCFA (25%)",
      daysInStage: 14,
      slaMaxDays: 15,
      agency: "Agence Douala",
      clientId: "cl-6",
      landTitle: "TF N° 14892/Océan",
      cobacRatio: "22.3%",
      decisionStatus: "Minute notariée transmise à la Conservation",
      title: "DUC-04590 · TCHOUNGUI Alain (Kribi)",
      description: "Rédaction convention notariée & inscription d'hypothèque 1er rang MINDCAF (Titre Foncier N° 14892/Océan).",
      priority: "Medium",
      dueDate: "22 Sept 2026",
      progress: 60,
      owner: taskOwners.meNkouendjin,
      team: "Étude Notariale",
      insights: [
        { label: "Attachments", count: 6 },
        { label: "Comments", count: 4 },
        { label: "Documents", count: 8 },
      ],
    },
  ],
  disbursements: [
    {
      id: "cfc-task-7",
      ducId: "DUC-04410",
      clientName: "EBAH Rodrigue",
      projectTitle: "Travaux Finition Mendong",
      amount: "18 000 000 FCFA",
      amountRaw: 18000000,
      equityContribution: "3 600 000 FCFA (20%)",
      daysInStage: 6,
      slaMaxDays: 12,
      agency: "Agence Yaoundé",
      clientId: "cl-7",
      landTitle: "TF N° 6321/Mfoundi",
      cobacRatio: "25.0%",
      decisionStatus: "Tranche 2 (40%) ordonnancée SYSTAC",
      title: "DUC-04410 · EBAH Rodrigue (Mendong)",
      description: "Validation 2ème déblocage travaux (40% - 7 200 000 FCFA) sur PV de Valeur Disponible (Gros œuvre achevé).",
      priority: "High",
      dueDate: "20 Sept 2026",
      progress: 60,
      owner: taskOwners.henrietteBella,
      team: "Comptabilité SYSTAC",
      insights: [
        { label: "Attachments", count: 14 },
        { label: "Comments", count: 9 },
        { label: "Documents", count: 16 },
      ],
    },
    {
      id: "cfc-task-11",
      ducId: "DUC-04520",
      clientName: "METOUGUE Alice",
      projectTitle: "Extension Akwa",
      amount: "20 000 000 FCFA",
      amountRaw: 20000000,
      equityContribution: "4 000 000 FCFA (20%)",
      daysInStage: 5,
      slaMaxDays: 12,
      agency: "Agence Douala",
      clientId: "cl-3",
      landTitle: "TF N° 9912/Wouri",
      cobacRatio: "27.1%",
      decisionStatus: "Tranche 1 débloquée, Tranche 2 en attente PV BET",
      title: "DUC-04520 · METOUGUE Alice (Douala Akwa)",
      description: "Vérification des factures acquittées fournisseur de matériaux avant ordre de virement Tranche 2.",
      priority: "Medium",
      dueDate: "25 Sept 2026",
      progress: 50,
      owner: taskOwners.henrietteBella,
      team: "Comptabilité SYSTAC",
      insights: [
        { label: "Attachments", count: 9 },
        { label: "Comments", count: 3 },
        { label: "Documents", count: 12 },
      ],
    },
  ],
  closing_release: [
    {
      id: "cfc-task-8",
      ducId: "DUC-03890",
      clientName: "KAMGA Pascal",
      projectTitle: "Crédit 15 ans Villa Bastos",
      amount: "30 000 000 FCFA",
      amountRaw: 30000000,
      equityContribution: "6 000 000 FCFA (20%)",
      daysInStage: 3,
      slaMaxDays: 7,
      agency: "Agence Yaoundé",
      clientId: "cl-8",
      landTitle: "TF N° 2011/Mfoundi",
      cobacRatio: "0.0%",
      decisionStatus: "Mainlevée d'hypothèque délivrée MINDCAF",
      title: "DUC-03890 · KAMGA Pascal (Bastos)",
      description: "Extinction complète de la dette (15 ans). Émission de l'acte de mainlevée d'hypothèque & restitution Titre Foncier original.",
      priority: "Low",
      dueDate: "28 Août 2026",
      progress: 100,
      owner: taskOwners.suzanneNga,
      team: "Direction Crédit",
      insights: [
        { label: "Attachments", count: 18 },
        { label: "Comments", count: 6 },
        { label: "Documents", count: 20 },
      ],
    },
  ],
};
