export interface ClientDocument {
  name: string;
  category: "Identité" | "Foncier" | "Technique" | "Finances" | "Assurance";
  status: "Validé" | "En attente" | "En cours" | "Rejeté";
  date: string;
  ref?: string;
}

export interface ClientVisa {
  stage: string;
  actor: string;
  decision: "Favorable" | "En attente" | "Réserves";
  date: string;
  comment: string;
}

export interface ClientItem {
  id: string;
  ducId: string;
  name: string;
  avatarTone: string;
  email: string;
  phone: string;
  region: string;
  agency: string;
  profession: string;
  employer: string;
  projectType: string;
  loanAmount: string;
  savingsTarget: string;
  savingsCurrent: string;
  savingsPercent: number;
  monthlyIncome: string;
  monthlyPayment: string;
  debtRatio: string;
  landTitle: string;
  durationYears: number;
  rate: string;
  accountNumber: string;
  notaryAssigned: string;
  betAssigned: string;
  officer: string;
  phase: "Épargne & KYC" | "Risques & BET" | "Comités CGR/CRC" | "Notaire & Hypothèque" | "Déblocages Travaux" | "Clôture & Mainlevée";
  status: "Conforme" | "En Examen" | "Pièces Manquantes" | "Accordé" | "Mainlevée";
  lastActivity: string;
  completionPercent: number;
  documents: ClientDocument[];
  visas: ClientVisa[];
}

export const clientsData: ClientItem[] = [
  {
    id: "cl-1",
    ducId: "DUC-2026-04829",
    name: "ABANDA Eric",
    avatarTone: "bg-blue-500/15 text-blue-700 dark:text-blue-300",
    email: "e.abanda@camtel.cm",
    phone: "+237 699 45 12 80",
    region: "Centre (Yaoundé)",
    agency: "Agence Yaoundé Centre",
    profession: "Cadre Télécoms",
    employer: "CAMTEL Cameroun (CDI)",
    projectType: "Construction Villa R+1",
    loanAmount: "24 000 000 FCFA",
    savingsTarget: "4 800 000 FCFA",
    savingsCurrent: "4 800 000 FCFA",
    savingsPercent: 100,
    monthlyIncome: "1 250 000 FCFA",
    monthlyPayment: "215 000 FCFA / mois",
    debtRatio: "17.2%",
    landTitle: "TF N° 12844/Mfoundi",
    durationYears: 15,
    rate: "5.5% (Taux Bonifié)",
    accountNumber: "CPT-EH-2024-00481",
    notaryAssigned: "Me Emmanuel Nkouendjin (Yaoundé)",
    betAssigned: "BET CIRA Cameroun",
    officer: "Mme Mbezele (Agence Centre)",
    phase: "Épargne & KYC",
    status: "Conforme",
    lastActivity: "Il y a 10 min",
    completionPercent: 100,
    documents: [
      { name: "Carte Nationale d'Identité (CNI)", category: "Identité", status: "Validé", date: "12/08/2026", ref: "CNI-10294810" },
      { name: "Certificat de Propriété Foncier récent", category: "Foncier", status: "Validé", date: "15/08/2026", ref: "CPF-2026-092" },
      { name: "Devis Quantitatif Estimatif BET", category: "Technique", status: "Validé", date: "20/08/2026", ref: "BET-DQE-441" },
      { name: "3 Derniers Bulletins de Salaire", category: "Finances", status: "Validé", date: "14/08/2026", ref: "SAL-CAMTEL-08" },
      { name: "Permis de Bâtir / CU", category: "Technique", status: "Validé", date: "25/08/2026", ref: "CUY-PB-2026" },
      { name: "Police d'Assurance Incendie & ADI", category: "Assurance", status: "Validé", date: "02/09/2026", ref: "AXA-ADI-881" },
    ],
    visas: [
      { stage: "G1 · Enrôlement & KYC", actor: "Mme Mbezele (Agence)", decision: "Favorable", date: "14/08/2026", comment: "Dossier d'épargne 100% complété, apport disponible sur Carthago." },
      { stage: "G3 · Risques & BET", actor: "Ing. Tchounke (BET CIRA)", decision: "Favorable", date: "28/08/2026", comment: "Terrain stable, devis cohérent avec les ratios mercuriales CFC." },
      { stage: "G6 · Comité CGR", actor: "Secrétariat CGR CFC", decision: "En attente", date: "Programmée 15/09", comment: "Inscrit à l'ordre du jour du prochain comité de crédit." },
    ],
  },
  {
    id: "cl-2",
    ducId: "DUC-2026-04910",
    name: "FOKAM Emmanuel",
    avatarTone: "bg-emerald-500/15 text-emerald-700 dark:text-emerald-300",
    email: "emmanuel.fokam@gmail.com",
    phone: "+237 677 88 99 00",
    region: "Ouest (Bafoussam)",
    agency: "Agence Bafoussam",
    profession: "Commerçant Import-Export",
    employer: "Établissements Fokam & Cie",
    projectType: "Acquisition Terrain + Bâtisse",
    loanAmount: "18 000 000 FCFA",
    savingsTarget: "3 600 000 FCFA",
    savingsCurrent: "850 000 FCFA",
    savingsPercent: 23,
    monthlyIncome: "850 000 FCFA",
    monthlyPayment: "178 000 FCFA / mois",
    debtRatio: "20.9%",
    landTitle: "TF N° 4510/Mifi",
    durationYears: 12,
    rate: "5.75%",
    accountNumber: "CPT-EH-2025-00112",
    notaryAssigned: "Me Henri Kamdem (Bafoussam)",
    betAssigned: "Cabinet Bati-Etudes Bafoussam",
    officer: "M. Tagne (Agence Bafoussam)",
    phase: "Épargne & KYC",
    status: "Pièces Manquantes",
    lastActivity: "Hier",
    completionPercent: 40,
    documents: [
      { name: "Carte Nationale d'Identité (CNI)", category: "Identité", status: "Validé", date: "10/08/2026" },
      { name: "Certificat de Propriété Foncier récent", category: "Foncier", status: "En attente", date: "À renouveler" },
      { name: "Devis Quantitatif Estimatif BET", category: "Technique", status: "En cours", date: "En préparation" },
      { name: "3 Derniers Relevés Bancaires d'Activité", category: "Finances", status: "Validé", date: "18/08/2026" },
      { name: "Permis de Bâtir / CU", category: "Technique", status: "En attente", date: "À fournir" },
      { name: "Police d'Assurance Incendie & ADI", category: "Assurance", status: "En attente", date: "À souscrire" },
    ],
    visas: [
      { stage: "G1 · Enrôlement & KYC", actor: "M. Tagne (Agence Bafoussam)", decision: "Réserves", date: "22/08/2026", comment: "Apport personnel en cours de constitution (23%). Relance pièces foncières." },
    ],
  },
  {
    id: "cl-3",
    ducId: "DUC-2026-04750",
    name: "MBALLA Jean-Paul",
    avatarTone: "bg-amber-500/15 text-amber-700 dark:text-amber-300",
    email: "jp.mballa@minmidt.gov.cm",
    phone: "+237 690 12 34 56",
    region: "Centre (Yaoundé)",
    agency: "Agence Yaoundé Olembé",
    profession: "Fonctionnaire MINMIDT",
    employer: "Ministère des Mines & Industrie",
    projectType: "Construction Duplex Olembé",
    loanAmount: "18 500 000 FCFA",
    savingsTarget: "3 700 000 FCFA",
    savingsCurrent: "3 700 000 FCFA",
    savingsPercent: 100,
    monthlyIncome: "620 000 FCFA",
    monthlyPayment: "165 000 FCFA / mois",
    debtRatio: "26.6%",
    landTitle: "TF N° 21890/Mfoundi (Olembé)",
    durationYears: 15,
    rate: "5.25%",
    accountNumber: "CPT-EH-2024-00714",
    notaryAssigned: "Me Jacques Bisseck",
    betAssigned: "Labo Génie Civil Yaoundé",
    officer: "M. Ndi (Agence Olembé)",
    phase: "Risques & BET",
    status: "En Examen",
    lastActivity: "01 Sept 2026",
    completionPercent: 85,
    documents: [
      { name: "Carte Nationale d'Identité (CNI)", category: "Identité", status: "Validé", date: "02/08/2026" },
      { name: "Certificat de Propriété Foncier récent", category: "Foncier", status: "Validé", date: "10/08/2026" },
      { name: "Devis Quantitatif Estimatif BET", category: "Technique", status: "Validé", date: "19/08/2026" },
      { name: "3 Derniers Bulletins de Salaire", category: "Finances", status: "Validé", date: "05/08/2026" },
      { name: "Permis de Bâtir Communauté Urbaine", category: "Technique", status: "Validé", date: "29/08/2026" },
      { name: "Police d'Assurance Incendie & ADI", category: "Assurance", status: "En cours", date: "Souscription en agence" },
    ],
    visas: [
      { stage: "G1 · Enrôlement & KYC", actor: "M. Ndi (Agence Olembé)", decision: "Favorable", date: "12/08/2026", comment: "Agent public titulaire, prélèvement à la source validé." },
      { stage: "G3 · Risques & BET", actor: "Labo Génie Civil Yaoundé", decision: "Favorable", date: "30/08/2026", comment: "Sondage géotechnique satisfaisant, portance du sol conforme." },
    ],
  },
  {
    id: "cl-4",
    ducId: "DUC-2026-04812",
    name: "FOTSO Michel",
    avatarTone: "bg-purple-500/15 text-purple-700 dark:text-purple-300",
    email: "michel.fotso@groupe-sa.cm",
    phone: "+237 655 44 33 22",
    region: "Littoral (Douala)",
    agency: "Agence Douala Bonanjo",
    profession: "Directeur Financier",
    employer: "Groupe Industriel SA Douala",
    projectType: "Logement Standing Bonapriso",
    loanAmount: "35 000 000 FCFA",
    savingsTarget: "7 000 000 FCFA",
    savingsCurrent: "7 000 000 FCFA",
    savingsPercent: 100,
    monthlyIncome: "2 400 000 FCFA",
    monthlyPayment: "310 000 FCFA / mois",
    debtRatio: "12.9%",
    landTitle: "TF N° 8904/Wouri (Bonapriso)",
    durationYears: 18,
    rate: "5.0%",
    accountNumber: "CPT-EH-2023-00332",
    notaryAssigned: "Me Mireille Douala Manga Bell",
    betAssigned: "BUREAU VERITAS Douala",
    officer: "Mme Manga (Agence Bonanjo)",
    phase: "Risques & BET",
    status: "En Examen",
    lastActivity: "28 Août 2026",
    completionPercent: 90,
    documents: [
      { name: "Carte Nationale d'Identité (CNI)", category: "Identité", status: "Validé", date: "05/08/2026" },
      { name: "Certificat de Propriété Foncier récent", category: "Foncier", status: "Validé", date: "12/08/2026" },
      { name: "Devis Quantitatif Estimatif BET", category: "Technique", status: "Validé", date: "24/08/2026" },
      { name: "3 Derniers Bulletins & Attestation Emploi", category: "Finances", status: "Validé", date: "08/08/2026" },
      { name: "Permis de Bâtir CUD", category: "Technique", status: "Validé", date: "25/08/2026" },
      { name: "Police d'Assurance Incendie & ADI", category: "Assurance", status: "Validé", date: "27/08/2026" },
    ],
    visas: [
      { stage: "G1 · Enrôlement & KYC", actor: "Mme Manga (Agence)", decision: "Favorable", date: "15/08/2026", comment: "Revenus élevés, solvabilité excellente, apport mobilisé." },
      { stage: "G3 · Risques & BET", actor: "BUREAU VERITAS Douala", decision: "Favorable", date: "28/08/2026", comment: "Dossier technique de très haute qualité, permis conforme." },
    ],
  },
  {
    id: "cl-5",
    ducId: "DUC-2026-04655",
    name: "NGO NSOA Marie",
    avatarTone: "bg-rose-500/15 text-rose-700 dark:text-rose-300",
    email: "marie.ngonsoa@yahoo.fr",
    phone: "+237 696 22 11 00",
    region: "Centre (Yaoundé)",
    agency: "Agence Yaoundé Bastos",
    profession: "Enseignante Supérieur",
    employer: "Université de Yaoundé I",
    projectType: "Acquisition Logement Social SIC",
    loanAmount: "14 400 000 FCFA",
    savingsTarget: "2 880 000 FCFA",
    savingsCurrent: "2 880 000 FCFA",
    savingsPercent: 100,
    monthlyIncome: "580 000 FCFA",
    monthlyPayment: "135 000 FCFA / mois",
    debtRatio: "23.2%",
    landTitle: "TF N° 3110/Mfoundi (SIC Mbankolo)",
    durationYears: 15,
    rate: "5.25%",
    accountNumber: "CPT-EH-2024-00522",
    notaryAssigned: "Me Bello Ousmanou",
    betAssigned: "BET BTP Cameroun",
    officer: "M. Etoa (Agence Bastos)",
    phase: "Comités CGR/CRC",
    status: "Accordé",
    lastActivity: "25 Août 2026",
    completionPercent: 100,
    documents: [
      { name: "Carte Nationale d'Identité (CNI)", category: "Identité", status: "Validé", date: "01/08/2026" },
      { name: "Convention de Réservation SIC", category: "Foncier", status: "Validé", date: "05/08/2026" },
      { name: "Fiche Descriptive Logement SIC", category: "Technique", status: "Validé", date: "10/08/2026" },
      { name: "3 Bulletins de Solde Fonction Publique", category: "Finances", status: "Validé", date: "03/08/2026" },
      { name: "Certificat d'Urbanisme", category: "Technique", status: "Validé", date: "12/08/2026" },
      { name: "Assurance Emprunteur ADI", category: "Assurance", status: "Validé", date: "15/08/2026" },
    ],
    visas: [
      { stage: "G1 · Enrôlement & KYC", actor: "M. Etoa (Agence Bastos)", decision: "Favorable", date: "08/08/2026", comment: "Programme conventionné CFC-SIC, éligible taux bonifié." },
      { stage: "G3 · Risques & BET", actor: "BET BTP Cameroun", decision: "Favorable", date: "18/08/2026", comment: "Logement achevé, certificat de conformité disponible." },
      { stage: "G6 · Comité CGR", actor: "Comité CGR Siège", decision: "Favorable", date: "25/08/2026", comment: "Crédit accordé à l'unanimité (PV N° 2026/08/CGR-03)." },
    ],
  },
  {
    id: "cl-6",
    ducId: "DUC-2026-04590",
    name: "TCHOUNGUI Alain",
    avatarTone: "bg-indigo-500/15 text-indigo-700 dark:text-indigo-300",
    email: "alain.tchoungui@portkribi.cm",
    phone: "+237 671 90 80 70",
    region: "Sud (Kribi)",
    agency: "Agence Kribi",
    profession: "Ingénieur Port Autonome",
    employer: "Port Autonome de Kribi (PAK)",
    projectType: "Résidence Balnéaire Kribi",
    loanAmount: "28 000 000 FCFA",
    savingsTarget: "5 600 000 FCFA",
    savingsCurrent: "5 600 000 FCFA",
    savingsPercent: 100,
    monthlyIncome: "1 450 000 FCFA",
    monthlyPayment: "255 000 FCFA / mois",
    debtRatio: "17.5%",
    landTitle: "TF N° 6120/Océan (Kribi)",
    durationYears: 15,
    rate: "5.25%",
    accountNumber: "CPT-EH-2024-00639",
    notaryAssigned: "Me Jacques Bisseck",
    betAssigned: "BET Littoral Océan",
    officer: "Mme Bilong (Agence Kribi)",
    phase: "Notaire & Hypothèque",
    status: "Conforme",
    lastActivity: "22 Août 2026",
    completionPercent: 95,
    documents: [
      { name: "Carte Nationale d'Identité (CNI)", category: "Identité", status: "Validé", date: "10/07/2026" },
      { name: "Certificat de Propriété Foncier récent", category: "Foncier", status: "Validé", date: "15/07/2026" },
      { name: "Devis Quantitatif Estimatif BET", category: "Technique", status: "Validé", date: "22/07/2026" },
      { name: "Bulletins de Salaire PAK", category: "Finances", status: "Validé", date: "12/07/2026" },
      { name: "Permis de Bâtir Commune Kribi", category: "Technique", status: "Validé", date: "28/07/2026" },
      { name: "Police Incendie & ADI", category: "Assurance", status: "Validé", date: "05/08/2026" },
    ],
    visas: [
      { stage: "G1 · Enrôlement & KYC", actor: "Mme Bilong (Agence Kribi)", decision: "Favorable", date: "18/07/2026", comment: "Salarié PAK conventionné, domiciliation irrévocable." },
      { stage: "G3 · Risques & BET", actor: "BET Littoral Océan", decision: "Favorable", date: "02/08/2026", comment: "Étude géotechnique sableuse OK avec fondations adaptées." },
      { stage: "G6 · Comité CGR", actor: "Comité CGR", decision: "Favorable", date: "12/08/2026", comment: "Accordé avec hypothèque conventionnelle de 1er rang." },
      { stage: "G8 · Notaire & Cadastre", actor: "Me Jacques Bisseck", decision: "En attente", date: "22/08/2026", comment: "Rédaction de l'acte d'affectation hypothécaire en cours." },
    ],
  },
  {
    id: "cl-7",
    ducId: "DUC-2026-04410",
    name: "EBAH Rodrigue",
    avatarTone: "bg-teal-500/15 text-teal-700 dark:text-teal-300",
    email: "rodrigue.ebah@socatral.cm",
    phone: "+237 694 55 66 77",
    region: "Centre (Yaoundé)",
    agency: "Agence Yaoundé Mendong",
    profession: "Pharmacien Titulaire",
    employer: "Pharmacie du Centre Mendong",
    projectType: "Construction R+2 Locatif",
    loanAmount: "32 000 000 FCFA",
    savingsTarget: "6 400 000 FCFA",
    savingsCurrent: "6 400 000 FCFA",
    savingsPercent: 100,
    monthlyIncome: "1 800 000 FCFA",
    monthlyPayment: "295 000 FCFA / mois",
    debtRatio: "16.4%",
    landTitle: "TF N° 17400/Mfoundi (Mendong)",
    durationYears: 15,
    rate: "5.25%",
    accountNumber: "CPT-EH-2023-00812",
    notaryAssigned: "Me Emmanuel Nkouendjin",
    betAssigned: "BET CIRA Cameroun",
    officer: "M. Abessolo (Agence Mendong)",
    phase: "Déblocages Travaux",
    status: "Accordé",
    lastActivity: "20 Août 2026",
    completionPercent: 98,
    documents: [
      { name: "Carte Nationale d'Identité (CNI)", category: "Identité", status: "Validé", date: "05/06/2026" },
      { name: "Grosse d'Acte d'Hypothèque Notariée", category: "Foncier", status: "Validé", date: "15/07/2026" },
      { name: "Attestation Inscription Hypothèque Conservation", category: "Foncier", status: "Validé", date: "22/07/2026" },
      { name: "Rapport d'Attachement Tranche 1 (Fondations)", category: "Technique", status: "Validé", date: "10/08/2026" },
      { name: "Permis de Bâtir", category: "Technique", status: "Validé", date: "10/06/2026" },
      { name: "Police Incendie / Tous Risques Chantier", category: "Assurance", status: "Validé", date: "20/07/2026" },
    ],
    visas: [
      { stage: "G8 · Notariat", actor: "Me Emmanuel Nkouendjin", decision: "Favorable", date: "25/07/2026", comment: "Hypothèque inscrite sans opposition, grosse déposée au CFC." },
      { stage: "G7 · Déblocages", actor: "Direction Déblocages CFC", decision: "Favorable", date: "20/08/2026", comment: "Tranche 1 décaissée (12,8M FCFA). Tranche 2 en attente élévation." },
    ],
  },
  {
    id: "cl-8",
    ducId: "DUC-2026-04320",
    name: "NDONGO Valérie (Diaspora)",
    avatarTone: "bg-cyan-500/15 text-cyan-700 dark:text-cyan-300",
    email: "valerie.ndongo@chu-paris.fr",
    phone: "+33 6 12 34 56 78",
    region: "Diaspora (France)",
    agency: "Cellule Diaspora Siège",
    profession: "Médecin Hospitalier",
    employer: "Assistance Publique Hôpitaux de Paris (AP-HP)",
    projectType: "Villa Standing Yaoundé Simbock",
    loanAmount: "45 000 000 FCFA",
    savingsTarget: "9 000 000 FCFA",
    savingsCurrent: "9 000 000 FCFA",
    savingsPercent: 100,
    monthlyIncome: "4 200 € (~2 755 000 FCFA)",
    monthlyPayment: "395 000 FCFA / mois",
    debtRatio: "14.3%",
    landTitle: "TF N° 29410/Mfoundi (Simbock)",
    durationYears: 18,
    rate: "5.0%",
    accountNumber: "CPT-EH-2023-00045-DIA",
    notaryAssigned: "Me Mireille Douala Manga Bell",
    betAssigned: "Bureau Veritas Cameroun",
    officer: "M. Zogo (Cellule Diaspora)",
    phase: "Notaire & Hypothèque",
    status: "Conforme",
    lastActivity: "15 Août 2026",
    completionPercent: 92,
    documents: [
      { name: "Passeport & Carte Consulaire", category: "Identité", status: "Validé", date: "15/05/2026" },
      { name: "Certificat de Propriété Foncier", category: "Foncier", status: "Validé", date: "20/05/2026" },
      { name: "Devis Quantitatif Estimatif BET", category: "Technique", status: "Validé", date: "10/06/2026" },
      { name: "Fiches de Paie France & Avis d'Imposition", category: "Finances", status: "Validé", date: "18/05/2026" },
      { name: "Permis de Bâtir CUY", category: "Technique", status: "Validé", date: "02/07/2026" },
      { name: "Procuration Notariée Consulat Cameroun Paris", category: "Foncier", status: "Validé", date: "05/08/2026" },
    ],
    visas: [
      { stage: "G1 · Enrôlement Diaspora", actor: "M. Zogo (Cellule Diaspora)", decision: "Favorable", date: "25/05/2026", comment: "Virements réguliers SWIFT, apport 9M FCFA vérifié." },
      { stage: "G6 · Comité CGR", actor: "Comité CGR Siège", decision: "Favorable", date: "14/07/2026", comment: "Accord favorable pour 45M FCFA. Projet valorisant." },
      { stage: "G8 · Notariat", actor: "Me Douala Manga Bell", decision: "En attente", date: "15/08/2026", comment: "Procuration consulaire reçue, signature prévue sous 10 jours." },
    ],
  },
  {
    id: "cl-9",
    ducId: "DUC-2026-03890",
    name: "KAMGA Pascal",
    avatarTone: "bg-slate-500/15 text-slate-700 dark:text-slate-300",
    email: "p.kamga@bastos.cm",
    phone: "+237 699 01 02 03",
    region: "Centre (Yaoundé)",
    agency: "Agence Yaoundé Bastos",
    profession: "Avocat au Barreau",
    employer: "Cabinet Me Kamga & Associés",
    projectType: "Prêt Habitat Individuel (15 ans)",
    loanAmount: "16 000 000 FCFA",
    savingsTarget: "3 200 000 FCFA",
    savingsCurrent: "Soldé (Intégral)",
    savingsPercent: 100,
    monthlyIncome: "1 100 000 FCFA",
    monthlyPayment: "0 FCFA (Prêt Éteint)",
    debtRatio: "0.0%",
    landTitle: "TF N° 9812/Mfoundi",
    durationYears: 15,
    rate: "5.25%",
    accountNumber: "CPT-EH-2011-00219",
    notaryAssigned: "Me Emmanuel Nkouendjin",
    betAssigned: "Clôturé",
    officer: "Mme Mbezele (Agence Bastos)",
    phase: "Clôture & Mainlevée",
    status: "Mainlevée",
    lastActivity: "10 Août 2026",
    completionPercent: 100,
    documents: [
      { name: "Attestation de Remboursement Intégral", category: "Finances", status: "Validé", date: "02/08/2026" },
      { name: "Quittance de Solde Définitive Carthago", category: "Finances", status: "Validé", date: "04/08/2026" },
      { name: "Projet d'Acte de Mainlevée Notariée", category: "Foncier", status: "Validé", date: "08/08/2026" },
      { name: "Radiation Inscription Hypothécaire Conservation", category: "Foncier", status: "Validé", date: "10/08/2026" },
    ],
    visas: [
      { stage: "G4 · Clôture & Mainlevée", actor: "Direction Recouvrement CFC", decision: "Favorable", date: "10/08/2026", comment: "Prêt remboursé intégralement à terme. Mainlevée totale délivrée." },
    ],
  },
];
